#!/usr/bin/python


'''
- Cmdfoo v.alpha 2015-12-03 by hexufo.

Search commandlinefu.com database from the shell using the api.

Usage:   ./cmdfoo command
Example: ./cmdfoo ls

Do not use numbers as the command !
It seems like there is a bug in the api...

Get the latest version here:
https://github.com/hexufo/misc

You can find me in various places on the internet:
hexufo @ {wordpress, twitter, github, gmail}

- This software is distributed under the Unlicense:

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>
'''


import sys
import base64
import urllib2


def usage():
  print "Cmdfoo v.alpha 2015-12-03 by hexufo."
  print "Search commandlinefu.com database from the shell using the api."
  print
  print "  Usage: " + sys.argv[0] + " command"
  print "Example: " + sys.argv[0] + " ls"
  print
  print "Do not use numbers as the command !"
  print "It seems like there is a bug in the api..."

  sys.exit(1)


def get():
  start = "http://www.commandlinefu.com/commands/matching/"
  command = sys.argv[1]
  commandbase64 = base64.b64encode(command)
  end = "/plaintext"

  urlcmdfoo = start + command + "/" + commandbase64 + end

  try:
    req = urllib2.Request(urlcmdfoo)
    response = urllib2.urlopen(req)
    page = response.read()

    print page[:-1]
  except:
    print "Error..."
    sys.exit(1)


if __name__ == "__main__":
  if len(sys.argv) != 2:
    usage()
  else:
    get()

  sys.exit(0)


