#!/usr/bin/python


'''
- Elnmore v.alpha 2015-11-30 by hexufo.

(Electronics n more -> el n more -> elnmore)

This script gets the latest video titles and links from the
"electronics and more" youtube channel
(http://www.youtube.com/user/myvideoisonutube),
without using the youtube api.

Adatube, eevblogtube and elnmore are the same script with
different channel url.

Get the latest version here:
https://github.com/hexufo/misc

Project page on PyPI: https://pypi.python.org/pypi/misc-scripts

You can find me in various places on the internet:
hexufo @ {wordpress, twitter, github, gmail}

- This software is distributed under the Unlicense:

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>
'''


import urllib2
import re
import HTMLParser


try:
  url  = "https://www.youtube.com/user/myvideoisonutube/videos"
  req = urllib2.Request(url)
  response = urllib2.urlopen(req)
  htmlpage = response.read()

  search = re.findall('href=..watch.v..{1,11}.>.*</a>', htmlpage)

  h = HTMLParser.HTMLParser()

  youtube = "https://www.youtube.com"

  blue = '\033[1;34m'
  gray = '\033[1;30m'
  end = '\033[1;m'

  for i in range(0,len(search)):
    print blue + h.unescape(search[i][28:][:-4]) + end + " " + gray + youtube + search[i][6:][:-4][0:20] + end
except Exception, error_message:
  print "[-] Error: " + str(error_message)
  exit(1)


exit(0)


