#!/usr/bin/python


'''
- Github-random-avatar v.alpha 2015-12-31 by hexufo.

Download a random avatar image from github.

Usage: ./github-random-avatar number     - Get n avatars from github.

If no number is supplied, it will download just one avatar.

Get the latest version here:
https://github.com/hexufo/misc

Project page on PyPI: https://pypi.python.org/pypi/misc-scripts

You can find me in various places on the internet:
hexufo @ {wordpress, twitter, github, gmail}

- This software is distributed under the Unlicense:

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>
'''


import sys
import random
import urllib2


def usage():
  print "Github-random-avatar v.alpha 2015-12-31 by hexufo."
  print "Download a random avatar image from github."
  print
  print "Usage: " + sys.argv[0] + " number     - Get n avatars from github."
  print
  print "If no number is supplied, it will download just one avatar."


def getavatar(avatars):
  try:
    for i in range(0, avatars):
      rnd = random.randint(1, 16504248) # 2015-12-31: 1 to 16504248
      imgurl  = "https://avatars3.githubusercontent.com/u/"
      imgurl += str(rnd)
      print imgurl

      req = urllib2.Request(imgurl)
      response = urllib2.urlopen(req)
      img = response.read()

      imgfile = './' + str(rnd) + '.png'

      f = open(imgfile, 'w')
      f.write(img)
      f.close()
  except Exception, error_message:
    print "[-] Error: " + str(error_message)
    sys.exit(1)


if __name__ == "__main__":
  if (len(sys.argv) == 1):
    getavatar(1)
  elif (len(sys.argv) == 2):
    if (str(sys.argv[1]) == "-h" or str(sys.argv[1]) == "-help" or str(sys.argv[1]) == "--help"):
      usage()
      sys.exit(0)
    if (sys.argv[1].isdigit()):
      getavatar(int(sys.argv[1]))
    else:
      usage()
      sys.exit(1)
  else:
    usage()
    sys.exit(1)


  sys.exit(0)


