#!/usr/bin/python


'''
- Thinklightflash v.alpha 2015-12-14 by hexufo.

Flash the IBM X41 Thinklight n times.

Usage:   ./thinklightflash times updelay downdelay
Example: ./thinklightflash 5 0.3 0.3
Flashes 5 times, 0.3 seconds the led stays on and 0.3 seconds stays off.

You need root privileges to run this script.

More information here:
http://www.thinkwiki.org/wiki/ThinkLight

Get the latest version here:
https://github.com/hexufo/misc

You can find me in various places on the internet:
hexufo @ {wordpress, twitter, github, gmail}

- This software is distributed under the Unlicense:

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>
'''


import sys
import os
import time


def usage():
  print 'Thinklightflash v.alpha 2015-12-14 by hexufo.'
  print 'Flash the IBM X41 Thinklight n times.'
  print
  print 'Usage:   ' + sys.argv[0] + ' times updelay downdelay'
  print 'Example: ' + sys.argv[0] + ' 5 0.3 0.3'
  print 'Flashes 5 times, 0.3 seconds the led stays on and 0.3 seconds stays off.'
  print
  print 'You need root privileges to run this script.'


def flash(times, delay1, delay2):
  try:
    for i in range(times):
      os.system('/bin/echo 255 > /sys/class/leds/tpacpi\:\:thinklight/brightness')
      time.sleep(delay1)
      os.system('/bin/echo 0 > /sys/class/leds/tpacpi\:\:thinklight/brightness')
      time.sleep(delay2)
  except Exception, error_message:
      print '[-] Error: ' + str(error_message)
      sys.exit(1)


if __name__ == "__main__":
  if (len(sys.argv) <= 3):
    usage()
    sys.exit(1)
  elif (len(sys.argv) == 4):
    try:
      flash(int(sys.argv[1]), float(sys.argv[2]), float(sys.argv[3]))
    except:
      usage()
      #raise
      sys.exit(1)
  elif (len(sys.argv) > 4):
    usage()
    sys.exit(1)
  else:
    usage()
    sys.exit(1)


  sys.exit(0)


